spring:
  datasource:
    hikari:
      driver-class-name: ENC(mTMuDlEgv9s+2QTqCGGIc/pwPdg5DsRTUC3Bi0TTM07TbkR53YyoDw0rHu3kyWrK)
      jdbc-url: ENC(bU7yzOurSel7sIU4Jm/VjOA318ofL4BJ8kqTIm0GtAP+oOJbkMNYufzKmbaeSN8+oTI7xuW7qs0=)
      username: ENC(sKHNnnXUsHaey7HmUkowMvYqItqamwlE)
      password: ENC(HNX8xE4rV2fvwfiywvpWzu+B3emtPnqzo91pLD5VuQg=)
      maximum-pool-size: 5

server:
  log:
    path: logs\
