spring:
  datasource:
    hikari:
      driver-class-name: ENC(LDnEkdDhEEFe5z0JMSxvqr9TOw+GzpYz2Q+Gr9JhAeqOT06c35ZmFgifd+0LSRf+)
      jdbc-url: ENC(giEneamGauohJ1uvZBQiPJ9uYUlmYfTV5zAmsnTc2e3Wmpgsuhky+bYCWYWj089auIlvbXyff9w=)
      username: ENC(kOkVPEq71abMqcnIQ52N/6M/Um9Y5cvQ)
      password: ENC(2/1iTD8xCVf1jsf7968N5URcWv4sPIi+hmRihl9siV8=)
      maximum-pool-size: 5

server:
  log:
    path: logs