spring:
  datasource:
    hikari:
      driver-class-name: ENC(PmNwMSS3YUxPi0Ij9kE5PZjn5cbR1USdx3iyxN0QR4FcG3gHM52uhhT3gkkOo7dr)
      jdbc-url: ENC(UUcZyKbJPwUzlxCMrtffwgRlEXxWF1sAVIoAvaPmoWaIUKmsqd8uvYHnO9xH4gi1upFWt41321c=)
      username: ENC(wAcGLiLsuo+EKw9eiSAQXyAMkNhPWd/C)
      password: ENC(rueZ1lidsn4ci3fo6g6WzeTPID1BuR6L6SXwIx/sVzc=)
      maximum-pool-size: 5

server:
  log:
    path: logs\
